Add Stackoverflow Search Navigation
infokiller/web-search-navigator pull request #433
Opened 2022-09-26 04:56 UTC by margunwa123

Closes #429 

Checkpoints:
- [v] Stackoverflow seach result navigation
- [] Stackoverflow answers navigation

2022-11-01 20:27 UTC, infokiller commented
Looks good overall, left minor style comments. Please also update the CHANGELOG and README.

2022-11-01 20:27 UTC, infokiller requested changes

2022-11-01 20:27 UTC, infokiller commented on src/search_engines.js
> +      subtree: true,
Is this change related to the PR?

2022-11-01 20:27 UTC, infokiller commented on src/options_page.js
> +  'stackoverflow': ['https://stackoverflow.com/*', 'https://www.stackoverflow.com/*'],
Please change to `stack-overflow`, and for the JS variables below use `stackOverflow`

2022-11-01 20:27 UTC, infokiller commented on src/options_page.js
> +    const stackoverflow = document.getElementById('stackoverflow');
Please use stackOverflow

2023-05-29 09:48 UTC, HerrAugust commented
Hi everyone, I would be really interested in this feature as many others. Would it be possible to merge it? Or how can I help here?

Thanks!

2023-05-29 09:51 UTC, infokiller commented
Hi @HerrAugust 
There are minor style changes needed (see my comments), and some testing would be good. I guess there may be some merge conflicts since master advanced since then

I may look into it later

2023-07-25 05:15 UTC, closed without merging