feat: simulate middle click when opening in a new background tab
infokiller/web-search-navigator pull request #498
Opened 2023-03-27 05:00 UTC by MahdiNazemi

Closes #496.

2023-03-27 05:34 UTC, infokiller commented
Thanks for the contribution! I added one minor comment.
Did you test it manually, and does it resolve your issue?

2023-03-27 06:04 UTC, MahdiNazemi commented
> Thanks for the contribution! I added one minor comment. Did you test it manually, and does it resolve your issue?

Thank _you_. Yes, I tested it in Firefox, the only browser Temporary Containers supports, and it worked as expected.

I have trouble finding your comment.

2023-03-27 06:05 UTC, infokiller requested changes

2023-03-27 06:06 UTC, infokiller commented
> 



> > Thanks for the contribution! I added one minor comment. Did you test it manually, and does it resolve your issue?
> 
> Thank _you_. Yes, I tested it in Firefox, the only browser Temporary Containers supports, and it worked as expected.
> 
> I have trouble finding your comment.

Whoops, forgot to hit the "request changes" button. Now you should see it.
Thanks for testing!

2023-03-27 06:09 UTC, MahdiNazemi commented on src/main.js
> +        });
Yes, the parameters are exactly the same, and your comment is valid.

Temporary Containers defines an event listener only on the `mouseup` event, and I had initially defined only that. Later, I also added `mousedown` to really mimic the middle click. Should I keep both and name the option middle click or only keep `mouseup` and name the option something like middle click release?

2023-03-27 15:19 UTC, MahdiNazemi commented on src/main.js
> +        });
Done!

2023-03-28 05:37 UTC, merged

2023-03-28 05:38 UTC, infokiller commented
Looks great, merged it. I hope to release a new version to the stores (Chrome and Firefox) in the next few days.